Demonstrate the output using a new test
Test doesn't actually assert anything, but the output demonstrates the
problem:

```
❯ go test go.uber.org/zap/zaptest
--- FAIL: TestExampleLog (0.00s)
    logger.go:146: 2026-01-09T01:18:36.655-0800	INFO	Where am I?
FAIL
FAIL	go.uber.org/zap/zaptest	0.327s
FAIL
```

The output is attributed to zaptest/logger.go line 146 where the `t.Log`
takes place, instead of logger_test.go.

This has been observed before: https://github.com/uber-go/zap/issues/1493